/*
RailControl - Model Railway Control Software

Copyright (c) 2017-2019 Dominik (Teddy) Mahrer - www.railcontrol.org

RailControl is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3, or (at your option) any
later version.

RailControl is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with RailControl; see the file LICENCE. If not see
<http://www.gnu.org/licenses/>.
*/

#include "Languages.h"
#include "Utils/Utils.h"









const char* Languages::languages[MaxTexts][MaxLanguages] =
{
/* Text180Deg */ { "180 degrees", "180 Grad", "180 grados" },
/* Text90DegAntiClockwise */ { "90 degrees anti-clockwise", "90 Grad gegen den Uhrzeigersinn", "90 grados en el sentido contrario de las agujas del reloj" },
/* Text90DegClockwise */ { "90 degrees clockwise", "90 Grad im Uhrzeigersinn", "90 grados en el sentido de las agujas del reloj" },
/* TextAccessories */ { "Accessories", "Zubehörartikel", "Acesorios" },
/* TextAccessory*/ { "accessory", "Zubehörartikel", "acesorio" },
/* TextAccessoryAddressDccTooHigh */ { "Addresses higher then 2044 are not supported by DCC", "Adressen grösser als 2044 werden nicht unterstützt von DCC", "Direcciones más grandes que 2044 no están compatibles con DCC" },
/* TextAccessoryAddressMmTooHigh */ { "Addresses higher then 320 are not supported by MM1/MM2", "Adressen grösser als 320 werden nicht unterstützt von MM1/MM2", "Direcciones más grandes que 320 no están compatibles con MM1/MM2" },
/* TextAccessoryDeleted */ { "Accessory {0} deleted", "Zubehörartikel {0} gelöscht", "Accessorio {0} eliminado" },
/* TextAccessoryDoesNotExist */ { "Acessory does not exist", "Zubehörartikel existiert nicht", "Acesorio no existe" },
/* TextAccessoryIsLocked */ { "Accessory {0} is locked", "Zubehörartikel {0} ist gesperrt", "Acesorio {0} está bloqueado" },
/* TextAccessorySaved */ { "Accessory {0} saved", "Zubehörartikel {0} gespeichert", "Acesorio {0} guardado" },
/* TextAccessoryStateIsGreen */ { "Accessory state of {0} is now green", "Der Status des Zubehörartikels ist nun grün", "El estado del accessorio está verde" },
/* TextAccessoryStateIsRed */ { "Accessory state of {0} is now red", "Der Status des Zubehörartikels ist nun rot", "El estado del accessorio está rojo" },
/* TextAccessoryUpdated */ { "Accessory {0} updated", "Zubehörartikel {0} aktualisiert", "Accessorio {0} actualizado" },
/* TextAddAccessory */ { "Add accessory", "Zubehörartikel hinzufügen", "Añadir acesorio" },
/* TextAddFeedback */ { "Add feedback", "Rückmelder hinzufügen", "Añadir retroseñal" },
/* TextAddSignal */ { "Add signal", "Signal hinzufügen", "Añadir señal" },
/* TextAddStreet */ { "Add street", "Fahrstrasse hinzufügen", "Añadir itinerario" },
/* TextAddSwitch */ { "Add switch", "Weiche hinzufügen", "Añadir desvío" },
/* TextAddTrack */ { "Add track", "Gleis hinzufügen", "Añadir vía" },
/* TextAddingFeedback */ { "Adding feedback {0}", "Rückmelder {0} hinzugefügt", "Retroseñal añadido" },
/* TextAddress */ { "Address", "Adresse", "Dirección" },
/* TextAddressMustBeHigherThen0 */ { "Address must be higher then 0", "Adresse muss grösser sein als 0", "Dirección tiene que ser mas que 0" },
/* TextAllTrains */ { "all trains", "alle Züge", "todos los trenes" },
/* TextAllowedTrains */ { "Allowed trains:", "Erlaubte Züge", "Trenes permitidos" },
/* TextAreYouSureToDelete */ { "Are you sure you really want to delete {0}?", "Sind sie sicher, dass sie {0} löschen möchten?", "Está usted seguro, que usted quiere eliminar {0}?" },
/* TextAutomaticallyAddUnknownFeedbacks */ { "Automatically add unknown feedbacks", "Füge unbekannte Rückmelder automatisch hinzu", "Añadir retroseñales desconosidos automaticamente" },
/* TextAutomode */ { "Automode", "Automode", "Autómodo" },
/* TextBasic */ { "Basic data", "Basisdaten", "Datos basicos" },
/* TextBlockTrack */ { "Block track", "Blockiere Gleis", "Bloquear vía" },
/* TextBridge */ { "Bridge", "Brücke", "Puente" },
/* TextBufferStop */ { "End / Buffer Stop", "Ende / Prellbock", "Final / Tope" },
/* TextConnectionReset */ { "Connection reset", "Verbindung zurückgesetzt", "Conexión reajustado" },
/* TextControl */ { "Control", "Zentrale", "Control" },
/* TextControlDeleted */ { "Control {0} deleted", "Zentrale {0} gelöscht", "Control {0} eliminado" },
/* TextControlDoesNotExist */ { "Control does not exist", "Zentrale existiert nicht", "Control no existe" },
/* TextControlSaved */ { "Control {0} saved", "Zentrale {0} gespeichert", "Control {0} guardado" },
/* TextControls */ { "Controls", "Zentralen", "Controls" },
/* TextCreepAt */ { "Creep at", "Schleichgeschwindigkeit bei", "Velocidad a rastras a" },
/* TextCreepingSpeed */ { "Creeping speed", "Kriech Geschwindigkeit", "Velocidad a rastras" },
/* TextDebounceThreadStarted */ { "Debounce thread started", "Entprellthread gestartet", "Antirebote thread encendido" },
/* TextDebounceThreadTerminated */ { "Debounce thread terminated", "Entprellthread beedet", "Antirebote thread apagado" },
/* TextDebouncer */ { "Debouncer", "Entpreller", "Antirebote" },
/* TextDefaultSwitchingDuration */ { "Default switching duration (ms)", "Standard Schaltzeit (ms)", "Duración de conmutación por defecto (ms)" },
/* TextDelete */ { "Delete", "Löschen", "Eliminar" },
/* TextDeleteAccessory */ { "Delete accessory", "Zubehörartickel löschen", "Eliminar accesorio" },
/* TextDeleteControl */ { "Delete control", "Zentrale löschen", "Eliminar control" },
/* TextDeleteFeedback */ { "Delete feedback", "Rückmelder löschen", "Eliminar retroseñal" },
/* TextDeleteLayer */ { "Delete layer", "Schicht löschen", "Eliminar capa" },
/* TextDeleteLoco */ { "Delete locomotive", "Lokomotive löschen", "Eliminar locomotora" },
/* TextDeleteSignal */ { "Delete signal", "Signal löschen", "Eliminar señal" },
/* TextDeleteStreet */ { "Delete street", "Fahrstrasse löschen", "Eliminar itinerario" },
/* TextDeleteSwitch */ { "Delete switch", "Weiche löschen", "Eliminar desvío" },
/* TextDeleteTrack */ { "Delete track", "Gleis löschen", "Eliminar vía" },
/* TextDifferentDirections */ { "Locomotive and street {0} have different running directions", "Lok und Fahrstrasse {0} haben verschiedene Fahrtrichtungen", "Tren e itinerario tienen sentidos de la marcha differentes" },
/* TextDifferentPushpullTypes */ { "Locomotive and street {0} have different push-pull types", "Lok und Fahrstrasse {0} haben verschiedene Wendezugeinstellungen", "Tren e itinerario tienen ajustes de push-pull differentes" },
/* TextDoNotCare */ { "Do not care", "Egal", "No importa" },
/* TextDuration */ { "Switching duration (ms)", "Schaltzeit (ms)", "Duración de conmutación (ms)" },
/* TextEdit */ { "Edit", "Bearbeiten", "Editar" },
/* TextEditAccessory */ { "Edit accessory", "Zubehörartickel bearbeiten", "Editar acesorio" },
/* TextEditFeedback */ { "Edit feedback", "Rückmelder bearbeiten", "Editar retroseñal" },
/* TextEditSignal */ { "Edit signal", "Signal bearbeiten", "Editar señal" },
/* TextEditStreet */ { "Edit street", "Fahrstrasse bearbeiten", "Editar itinerario" },
/* TextEditSwitch */ { "Edit switch", "Weiche bearbeiten", "Editar desvío" },
/* TextEditTrack */ { "Edit track", "Gleis bearbeiten", "Editar vía" },
/* TextExecutingStreet */ { "Executing street {0}", "Führe Fahrstrasse {0} aus", "Ejecutando itinerario {0}" },
/* TextFeedback */ { "feedback", "Rückmelder", "retroseñal" },
/* TextFeedbackChange */ { "State of pin {0} on S88 module {1} is {2}", "Status von Pin {0} an S88 Modul {1} ist {2}", "Estado de contacto {0} del S88 módulo {1} está {2}" },
/* TextFeedbackDeleted */ { "Feedback {0} deleted", "Rückmelder {0} gelöscht", "Retroseñal {0} eliminado" },
/* TextFeedbackDoesNotExist */ { "Feedback does not exist", "Rückmelder existiert nicht", "Retroseñal no existe" },
/* TextFeedbackSaved */ { "Feedback {0} saved", "Rückmelder {0} gespeichert", "Retroseñal {0} guardado" },
/* TextFeedbackStateIsOff */ { "Feedback state of {0} is now off", "Der Status des Rückmelders ist nun aus", "El estado de la retroseñal {0} está apagado" },
/* TextFeedbackStateIsOn */ { "Feedback state of {0} is now on", "Der Status des Rückmelders ist nun ein", "El estado de la retroseñal {0} está encendido" },
/* TextFeedbackUpdated */ { "Feedback {0} updated", "Rückmelder {0} aktualisiert", "Retroseñal {0} actualizado" },
/* TextFeedbacks */ { "Feedbacks", "Rückmelder", "Retroseñales" },
/* TextFromTrack */ { "From track", "Von Gleis", "De vía" },
/* TextGreen */ { "green", "grün", "verde" },
/* TextHeightIs0 */ { "Height is zero", "Höhe ist null", "Altura está zero" },
/* TextHsi88Configured */ { "{0} ({1}/{2}/{3}) S88 modules configured.", "{0} ({1}/{2}/{3}) S88 Module konfiguriert", "{0} ({1}/{2}/{3}) S88 módulos configurado" },
/* TextHsi88ErrorConfiguring */ { "Unable to configure HSI-88. HSI-88 returned {0} configured modules", "HSI-88 kann nicht konfiguriert werden. HSI-88 meldet {0} module", "Imposible configurar HSI-88. HSI-88 denuncia {0} módulos" },
/* TextHttpConnectionClose */ { "HTTP connection {0}: close", "HTTP Verbindung {0}: geschlossen", "HTTP connectión {0}: cerrado" },
/* TextHttpConnectionNotFound */ { "HTTP connection {0}: 404 Not found: {1}", "HTTP Verbindung {0}: Nicht gefunden: {1}", "HTTP connectión {0}: no encontrado" },
/* TextHttpConnectionNotImplemented */ { "HTTP connection {0}: HTTP method {1} not implemented", "HTTP Verbindung {0}: Methode {1} nicht implementiert", "HTTP connectión {0}: no implementado" },
/* TextHttpConnectionOpen */ { "HTTP connection {0}: open", "HTTP Verbindung {0}: geöffnet", "HTTP connectión {0}: abierto" },
/* TextHttpConnectionRequest */ { "HTTP connection {0}: Request: {1} {2}", "HTTP Verbindung {0}: Anfrage {1} {2}", "HTTP connectión {0}: solicitud: {1} {2}" },
/* TextIPAddress */ { "IP address", "IP Adresse", "Dirección IP" },
/* TextInvalidDataReceived */ { "Invalid data received", "Ungültige Daten empfangen", "Recibido datos non validos" },
/* TextInverted */ { "Inverted", "Invertiert", "Invertido" },
/* TextLayer1 */ { "Layer 1", "Schicht 1", "Capa 1" },
/* TextLayer1IsUndeletable */ { "Layer 1 is undeletable", "Schicht 1 ist unlöschbar", "Capa 1 no se puede eliminar" },
/* TextLayerDeleted */ { "Layer {0} deleted", "Schicht {0} gelöscht", "Capa {0} eliminado" },
/* TextLayerDoesNotExist */ { "Layer does not exist", "Schicht existiert nicht", "Capa no existe" },
/* TextLayerSaved */ { "Layer {0} saved", "Schicht {0} gespeichert", "Capa {0} guardado" },
/* TextLayerUpdated */ { "Layer {0} updated", "Schicht {0} aktualisiert", "Capa {0} actualizado" },
/* TextLayers */ { "Layers", "Schichten", "Capas" },
/* TextLeft */ { "left", "links", "izquierda" },
/* TextLength */ { "Length", "Länge", "Longitud" },
/* TextLink */ { "Link", "Link", "Enlace" },
/* TextLoadedAccessory */ { "Loaded accessory {0}: {1}", "Zubehörartikel {0} geladen: {1}", "Cargado accesorio {0}: {1}" },
/* TextLoadedControl */ { "Loaded control {0}: {1}", "Zentrale {0} geladen: {1}", "Cargado control {0}: {1}" },
/* TextLoadedFeedback */ { "Loaded feedback {0}: {1}", "Rückmelder {0} geladen: {1}", "Cargado retroseñal {0}: {1}" },
/* TextLoadedLayer */ { "Loaded layer {0}: {1}", "Schicht {0} geladen: {1}", "Cargado capa {0}: {1}" },
/* TextLoadedLoco */ { "Loaded locomotive {0}: {1}", "Lokomotive {0} geladen: {1}", "Cargado locomotora {0}: {1}" },
/* TextLoadedSignal */ { "Loaded signal {0}: {1}", "Signal {0} geladen: {1}", "Cargado señal {0}: {1}" },
/* TextLoadedStreet */ { "Loaded street {0}: {1}", "Fahrstrasse {0} geladen: {1}", "Cargado itinerario {0}: {1}" },
/* TextLoadedSwitch */ { "Loaded switch {0}: {1}", "Weiche {0} geladen: {1}", "Cargado desvío {0}: {1}" },
/* TextLoadedTrack */ { "Loaded track {0}: {1}", "Gleis {0} geladen: {1}", "Cargado vía {0}: {1}" },
/* TextLoco */ { "Locomotive", "Lokomotive", "Locomotora" },
/* TextLocoAddressDccTooHigh */ { "Addresses higher then 10239 are not supported by DCC", "Adressen grösser als 10239 werden nicht unterstützt von DCC", "Direcciones más grandes que 10239 no están compatibles con DCC" },
/* TextLocoAddressMmTooHigh */ { "Addresses higher then 80 are not supported by MM1/MM2", "Adressen grösser als 80 werden nicht unterstützt von MM1/MM2", "Direcciones más grandes que 80 no están compatibles con MM1/MM2" },
/* TextLocoDeleted */ { "Locomotive {0} deleted", "Lokomotive {0} gelöscht", "Locomotora {0} eliminado" },
/* TextLocoDirectionIsLeft */ { "Direction of locomotive {0} is now left", "Die Fahrtrichtung der Lok {0} ist links", "La dirección de la locomotora {0} está izquierda" },
/* TextLocoDirectionIsRight */ { "Direction of locomotive {0} is now right", "Die Fahrtrichtung der Lok {0} ist rechts", "La dirección de la locomotora {0} está derecha" },
/* TextLocoDoesNotExist */ { "Locomotive does not exist", "Lokomotive existiert nicht", "Locomotora no existe" },
/* TextLocoFunctionIsOff */ { "F{1} of locomotive {0} is now off", "F{1} der Lok {0} ist aus", "F{1} de la locomotora {0} está apagado" },
/* TextLocoFunctionIsOn */ { "F{1} of locomotive {0} is now on", "F{1} der Lok {0} ist an", "F{1} de la locomotora {0} está encendido" },
/* TextLocoHasReachedDestination */ { "Locomotive {0} has reached destination track {1} via street {2}", "Die Lokomotive {1} hat das Zeilgleis {1} über die Fahrstrasse {2} erreicht.", "La locomotora {0} ha llegado a su vía destino {1} vía itinerario {2}" },
/* TextLocoIsInAutoMode */ { "Locomotive {0} is in auto mode", "Die Lokomotive {0} in im Automatik-Betrieb", "La locomotora {0} está en el modo automático" },
/* TextLocoIsInManualMode */ { "Locomotive {0} is in manual mode", "Die Lokomotive {0} in im manuellen Betrieb", "La locomotora {0} está en el modo manual" },
/* TextLocoIsOnTrack */ { "Locomotive {0} is on track {1}", "Lokomotive {0} ist auf Gleis {1}", "Locomotora está sobre vía {1}" } ,
/* TextLocoIsReleased */ { "Locomotive {0} is released", "Lokomotive {0} ist freigegeben", "Locomotora {0} está desbloqueada" },
/* TextLocoSaved */ { "Locomotive {0} saved", "Lokomotive {0} gespeichert", "Locomotora {0} guardado" },
/* TextLocoSpeedIs */ { "Speed of locomotive {0} is now {1}", "Die Geschwindigkeit der Lok {0} ist {1}", "La velocidad de la locomotora {0} está {1}" },
/* TextLocoUpdated */ { "Locomotive {0} updated", "Lokomotive {0} aktualisiert", "Locomotora {0} actualizado" },
/* TextLocos */ { "Locos", "Lokomotiven", "Locomotoras" },
/* TextLongestUnused */ { "Longest unused", "Am längsten ungenutzt", "El más largo sin usar" },
/* TextManager */ { "Manager", "Manager", "Manager" },
/* TextMaxSpeed */ { "Maximum speed", "Maximale Geschwindigkeit", "Velocidad máxima" },
/* TextMaxTrainLength */ { "Maximal train length", "Maximale Zuglänge", "Longitud de tren maxima" },
/* TextMembers */ { "Members", "Teilnehmer", "Miembros" },
/* TextMinTrackLength */ { "Minimal track length", "Kürzestes Gleis", "Vía más corta" },
/* TextMinTrainLength */ { "Minimal train length", "Minimale Zuglänge", "Longitud de tren minima" },
/* TextMultipleUnit */ { "Multiple unit", "Mehrfachtraktion", "Unidad múltiple" },
/* TextName */ { "Name", "Name", "Nombre" },
/* TextNew */ { "New", "Neu", "Nuevo" },
/* TextNoPushPull */ { "no push-pull trains", "keine Wendezüge", "ningunos push-pull trenes" },
/* TextNoRotation */ { "No rotation", "Keine Drehung", "Ninguna rotación" },
/* TextNoS88Modules */ { "No S88 modules configured", "Keine S88 Module konfiguriert", "No hay módulos S88 configurado" },
/* TextNrOfFunctions */ { "Number of functions", "Anzahl der Funktionen", "Número de funciones" },
/* TextNrOfS88Modules */ { "# of S88 Modules (8 port)", "Anzahl S88 Module (8 Pin)", "Número de módulos S88 (8 contactos)" },
/* TextNrOfTracksToReserve */ { "# of Tracks to reserve", "Anzahl der zu reservierenden Gleise", "Reservar numero de vías" },
/* TextOff */ { "off", "aus", "apagado" },
/* TextOn */ { "on", "ein", "encendido" },
/* TextOverrunAt */ { "Overrun at", "Überfahrt bei", "Pasar a" },
/* TextPin */ { "Pin", "Anschluss", "Contacto" },
/* TextPosX */ { "Position X", "Position X", "Posición X" },
/* TextPosY */ { "Position Y", "Position Y", "Posición Y" },
/* TextPosZ */ { "Layer", "Schicht", "Capa" },
/* TextPosition */ { "Position", "Position", "Posición" },
/* TextPositionAlreadyInUse */ { "Position {0}/{1}/{2} is already used by {3} \"{4}\".", "Position {0}/{1}/{2} ist bereits verwendet von {3} \"{4}\".", "Positión {0}/{1}/{2} está usado de {3} \"{4}\"." },
/* TextProtocol */ { "Protocol", "Protocol", "Protocolo" },
/* TextProtocolNotSupported */ { "Protocol {0}is not supported by control. Please use one of: {1}", "Protokoll {0} wird nicht unterstützt von der Zentrale. Verwende eines aus {1}", "Protocolo {0}no compatible con esa control. Utilisa uno de {1}" },
/* TextPushPullOnly */ { "push-pull trains only", "nur Wendezüge", "solamente push-pull trenes" },
/* TextPushPullTrain */ { "Push-Pull train", "Wendezug", "Tren push-pull" },
/* TextRailControlStarted */ { "RailControl started", "RailControl wurde gestartet", "RailControl encendido" },
/* TextRandom */ { "Random", "Zufall", "Aleatorio" },
/* TextReceivedSignalKill */ { "Received a signal kill {0} times. Exiting without saving.", "Signal Kill {0} mal erhalten. Beende RailControl ohne zu speichern.", "Señal Kill recibido {0} veces. Apagando RailControl sin guardar." },
/* TextReceiverThreadStarted */ { "Receiver thread started", "Empfangs-Thread gestartet", "Thread recibiendo creado" },
/* TextRed */ { "red", "rot", "rojo" },
/* TextReducedSpeed */ { "Reduced speed", "Reduzierte Geschwindigkeit", "Velocidad reducido" },
/* TextReducedSpeedAt */ { "Reduce speed at", "Reduziere Geschwindigkeit bei", "Reducir velocidad a" },
/* TextRelease */ { "Release", "Freigeben", "Liberar" },
/* TextReleaseAccessory */ { "Release accessory", "Zubehörartikel freigeben", "Liberar acesorio" },
/* TextReleaseLoco */ { "Release locomotive", "Lokomotive freigeben", "Liberar locomotora" },
/* TextReleaseSignal */ { "Release signal", "Signal freigeben", "Liberar señal" },
/* TextReleaseStreet */ { "Release street", "Fahrstrasse freigeben", "Liberar itinerario" },
/* TextReleaseSwitch */ { "Release switch", "Weiche freigeben", "Liberar desvío" },
/* TextReleaseTrack */ { "Release track", "Gleis freigeben", "Liberar vía" },
/* TextReleaseWhenFree */ { "Release when free", "Freigeben wenn nicht besetzt", "Liberar si no está ocupado" },
/* TextRight */ { "right", "rechts", "derecha" },
/* TextRotation */ { "Rotation", "Drehung", "Rotación", },
/* TextSaving */ { "Saving {0}", "Speichere {0}", "Guardando {0}" },
/* TextSelectLocoForTrack */ {"Select locomotive for track {0}", "Wähle Lokomotive für Gleis {0}", "Selectione locomotora para vía {0}" },
/* TextSelectStreetBy */ { "Select street by", "Wähle die Fahrstrasse nach", "Selecctionar itinerario por" },
/* TextSenderSocketCreated */ {"Sender socket created", "Sender socket erstellt", "Socket para enviar datos creado" },
/* TextSerialNumberIs */ { "Serialnumber is {0}", "Seriennummer ist {0}", "Número de serie es {0}" },
/* TextSerialPort */ { "Serial port", "Serieller Anschluss", "Puerto serie" },
/* TextSetLoco */ { "Set locomotive", "Setze Lokomotive", "Poner locomotora sobre vía" },
/* TextSettingAccessory */ { "Setting accessory {0}/{1} to {2}", "Setze Zubehörartikel {0}/{1} auf {2}", "Ajusto accesorio {0}/{1} a {2}" },
/* TextSettingAccessoryWithProtocol */ { "Setting accessory {0}/{1}/{2} to {3}", "Setze Zubehörartikel {0}/{1}/{2} auf {3}", "Ajusto accesorio {0}/{1}/{2} a {3}" },
/* TextSettingDirection */ { "Changing locomotive {0} direction", "Wechsle die Richtung der Lok {0}", "Cambio la direccion de la locomotora {0}" },
/* TextSettingDirectionWithProtocol */ { "Setting locomotive {0}/{1} to direction {2}", "Setze Lok {0}/{1} in Richtung {2}", "Ajusto la direccion de la locomotora {0}/{1} a {2}" },
/* TextSettingFunction */ { "Setting function {0} of locomotive {1} to {2}", "Setze Funktion {0} der Lok {1} auf {2}", "Ajusto la function {0} de la locomotora {1} a {2}" },
/* TextSettingFunctionWithProtocol */ { "Setting function {0} of locomotive {1}/{2} to {3}", "Setze Funktion {0} der Lok {1}/{2} auf {3}", "Ajusto la function {0} de la locomotora {1}/{2} a {3}" },
/* TextSettingSpeed */ { "Setting locomotive {0} to speed {1}", "Setze Lok {0} auf Geschwindigkeit {1}", "Ajusto la velocidad de la locomotora {0} a {1}" },
/* TextSettingSpeedDirectionLight */ { "Setting locomotive {0} to speed {1} and direction {2} and light {3}", "Setze Geschwindigkeit {1}, Richtung {2} und Licht {3} der Lok {0}", "Ajusto velocidad a {1}, direccion {2} y luz {3} de la locomotora {0}" },
/* TextSettingSpeedWithProtocol */ { "Setting locomotive {0}/{1} to speed {2}", "Setze Lok {0}/{1} auf Geschwindigkeit {2}", "Ajusto la velocidad de la locomotora {0}/{1} a {2}" },
/* TextSettings */ { "Settings", "Einstellungen", "Opciones" },
/* TextSettingsSaved */ { "Settings saved", "Einstellungen gespeichert", "Opciones guardado" },
/* TextSignal*/ { "signal ", "Signal", "señal" },
/* TextSignalDeleted */ { "Signal {0} deleted", "Signal {0} gelöscht", "Señal {0} eliminado" },
/* TextSignalDoesNotExist */ { "Signal does not exist", "Signal existiert nicht", "Señal no existe" },
/* TextSignalIsLocked */ { "Signal {0} is locked", "Signal {0} ist gesperrt", "Señal {0} está bloqueado" },
/* TextSignalSaved */ { "Signal {0} saved", "Signale {0} gespeichert", "Señal {0} guardado" },
/* TextSignalStateIsGreen */ { "Signal {0} is green", "Signal {0} ist grün", "Señal {0} está verde" },
/* TextSignalStateIsRed */ { "Signal {0} is red", "Signal {0} ist rot", "Señal {0} está roja" },
/* TextSignalUpdated */ { "Signal {0} updated", "Signal {0} aktualisiert", "Señal {0} actualizado" },
/* TextSignals */ { "Signals", "Signale", "Señales" },
/* TextSimple */ { "simple", "einfach", "simple" },
/* TextStartLoco */ { "Start locomotive", "Starte Lokomotive", "Poner locomotora en marcha" },
/* TextStopAt */ { "Stop at", "Anhalten bei", "Parar a" },
/* TextStopLoco */ { "Stop locomotive", "Stoppe Lokomotive", "Parar locomotora" },
/* TextStoppingRailControl */ { "Stopping RailControl", "Beende RailControl", "Apaga RailControl" },
/* TextStoppingRequestedBySignal */ { "Stopping RailControl requested by signal {0}", "Beenden von RailControl angefordert mit Signal {0}", "Apagar RailControl pedido con señal {0}" },
/* TextStoppingRequestedByWebClient */ { "Stopping RailControl requested by webclient", "Beenden von RailControl angefordert von Webclient", "Apagar RailControl pedido del webclient" },
/* TextStraight */ { "straight", "gerade", "recto" },
/* TextStreet*/ { "street", "Fahrstrasse", "itinerario" },
/* TextStreetDeleted */ { "Street {0} deleted", "Fahrstrasse {0} gelöscht", "Itinerario {0} eliminado" },
/* TextStreetDoesNotExist */ { "Street does not exist", "Fahrstrasse existiert nicht", "Itinerario no existe" },
/* TextStreetIsReleased */ { "Street {0} is released", "Fahrstrasse {0} ist freigegeben", "Itinerario {0} está desbloqueado" },
/* TextStreetSaved */ { "Street {0} saved", "Fahrstrasse {0} gespeichert", "Itinerario {0} guardado" },
/* TextStreetUpdated */ { "Street {0} updated", "Fahrstrasse {0} aktualisiert", "Itinerario {0} actualizado" },
/* TextStreets */ { "Streets", "Fahrstrassen", "Itinerarios" },
/* TextSwitch*/ { "switch", "Weiche", "desvío" },
/* TextSwitchDeleted */ { "Switch {0} deleted", "Weiche {0} gelöscht", "Desvío {0} eliminado" },
/* TextSwitchDoesNotExist */ { "Switch does not exist", "Weiche existiert nicht", "Desvío no existe" },
/* TextSwitchIsLocked */ { "Switch {0} is locked", "Weiche {0} ist gesperrt", "Desvío {0} está bloqueado" },
/* TextSwitchSaved */ { "Switch {0} saved", "Weiche {0} gespeichert", "Desvío {0} guardado" },
/* TextSwitchStateIsStraight */ { "Switch {0} is straight", "Weiche {0} ist geradeaus", "Desvío {0} está directo" },
/* TextSwitchStateIsTurnout */ { "Switch {0} is turnout", "Weiche {0} ist ablenkend", "Desvío {0} está desviado" },
/* TextSwitchUpdated */ { "Switch {0} updated", "Weiche {0} aktualisiert", "Desvío {0} actualizado" },
/* TextSwitches */ { "Switches", "Weichen", "Desvíos" },
/* TextSystemDefault */ { "Sysem default", "Systemeinstellung", "Configuración del sistema" },
/* TextTerminatingReceiverThread */ { "Terminating receiver thread", "Beende Empfangs-Thread", "Apagando thread recibiendo" },
/* TextTerminatingSenderSocket */ { "Terminating sender socket", "Beende Sende Socket", "Apagando socket enviando" },
/* TextTimestampAlreadySet */ { "Timestamp already set", "Zeit schon gesetzt", "Hora ya ajustado" },
/* TextTimestampNotSet */ { "Timestamp not set", "Zeit nicht gesetzt", "Hora no ajustado" },
/* TextTimestampSet */ { "Timestamp set", "Zeit gesetzt", "Hora ajustado" },
/* TextToTrack */ { "To track", "Zu Gleis", "Hasta vía" },
/* TextTooManyS88Modules */ { "Too many S88 modules configured: {0}. Max is {1}", "Zu viele S88 Module konfiguriert: {0}. Maximum ist {1}", "Demasiado módulos S88 configurado: {0}. El maximo es {1}" },
/* TextTrack*/ { "track", "Gleis", "vía" },
/* TextTrackDeleted */ { "Track {0} deleted", "Gleis {0} gelöscht", "Vía {0} eliminado" },
/* TextTrackDirectionToLeft */ { "Turn track direction to left", "Drehe Gleisrichtung nach links", "Gire la dirección de la vía hacia la izquierda" },
/* TextTrackDirectionToRight */ { "Turn track direction to right", "Drehe Gleisrichtung nach rechts", "Gire la dirección de la vía hacia la dereja" },
/* TextTrackDoesNotExist */ { "Track does not exist", "Gleis existiert nicht", "Vía no existe" },
/* TextTrackIsInUse */ { "Track {0} is in use", "Gleis {0} ist in Benutzung", "Vía {0} está en uso" },
/* TextTrackSaved */ { "Track {0} saved", "Gleis {0} gespeichert", "Vía {0} guardado" },
/* TextTrackStatusIsBlocked */ { "Track {0} is blocked", "Gleis {0} ist blockiert", "Vía {0} está bloqueado" },
/* TextTrackStatusIsBlockedAndOccupied */ { "Track {0} is blocked and occupied by {1}", "Gleis {0} ist blockiert und besetzt von {1}", "Vía {0} está bloqueado y ocupado por {1}" },
/* TextTrackStatusIsBlockedAndReserved */ { "Track {0} is blocked and reserved by {1}", "Gleis {0} ist blockiert und reserviert von {1}", "Vía {0} está bloqueado y reservado por {1}" },
/* TextTrackStatusIsFree */ { "Track {0} is free", "Gleis {0} ist frei", "Vía {0} está libre" },
/* TextTrackStatusIsOccupied */ { "Track {0} is occupied by {1}", "Gleis {0} ist besetzt von {0}", "Vía {0} está ocupada por {1}" },
/* TextTrackStatusIsReserved */ { "Track {0} is reserved by {1}", "Gleis {0} ist reserviert von {0}", "Vía {0} está reservada por {1}" },
/* TextTrackUpdated */ { "Track {0} updated", "Gleis {0} aktualisiert", "Vía {0} actualizado" },
/* TextTracks */ { "Tracks", "Gleise", "Vías" },
/* TextTrainIsToLong */ { "Train is to long for street {0}", "Zug ist zu lang für die Fahrstrasse {0}", "El tren es demasiado largo para el itinerario {0}" },
/* TextTrainIsToShort */ { "Train is to short for street {0}", "Zug ist zu kurz für die Fahrstrasse {0}", "El tren es demasiado corto para el itinerario {0}" },
/* TextTrainLenght */ { "Train length", "Zuglänge", "Longitud de tren" },
/* TextTravelSpeed */ { "Travel speed", "Reisegeschwindigkeit", "Velocidad de viaje" },
/* TextTunnelOneSide */ { "Tunnel (one side)", "Tunnel (eine Seite)", "Túnel (un lado)" },
/* TextTunnelTwoSides */ { "Tunnel (two sides)", "Tunnel (zwei Seiten)", "Túnel (dos lados)" },
/* TextTurn */ { "turn", "gebogen", "curvo" },
/* TextTurningBoosterOn */ { "Turning booster off", "Dektiviere booster", "Apagando booster" },
/* TextTurningBoosterOn */ { "Turning booster on", "Aktiviere booster", "Encendiendo booster" },
/* TextTurnout */ { "turnout", "abzweigend", "desviando" },
/* TextType */ { "Type", "Typ", "Typo" },
/* TextUnableToAddAccessory */ { "Unable to add accessory", "Nicht möglich den Zubehörartikel hinzuzufügen ", "Imposible añadir el acesorio" },
/* TextUnableToAddFeedback */ { "Unable to add feedback", "Nicht möglich den Rückmelder hinzuzufügen ", "Imposible añadir la retroseñal" },
/* TextUnableToAddLayer */ { "Unable to add layer", "Nicht möglich die Schicht hinzuzufügen ", "Imposible añadir la capa" },
/* TextUnableToAddLayer1 */ { "Unable to add initial layer 1", "Nicht möglich die Schicht 1 hinzuzufügen", "Imposible añadir capa 1" },
/* TextUnableToAddLoco */ { "Unable to add loco", "Nicht möglich die Lokomotive hinzuzufügen", "Impsible ańadir la locomotora" },
/* TextUnableToAddLocoToTrack */ { "Unable to add loco {0} to track {1}", "Nicht möglich die Lokomotive {0} auf Gleis {1} zu setzen", "Impsible poner la locomotora sobre vía {1}" },
/* TextUnableToAddSignal */ { "Unable to add signal", "Nicht möglich das Signal hinzuzufügen ", "Imposible añadir la señal" },
/* TextUnableToAddStreet */ { "Unable to add street", "Nicht möglich die Fahrstrasse hinzuzufügen ", "Imposible añadir el itinerario" },
/* TextUnableToAddSwitch */ { "Unable to add switch", "Nicht möglich die Weiche hinzuzufügen ", "Imposible añadir el desvío" },
/* TextUnableToAddTrack */ { "Unable to add track", "Nicht möglich das Gleis hinzuzufügen ", "Imposible añadir la vía" },
/* TextUnableToBindSocketToPort */ { "Unable to bind connection to port {0}", "Binden der Verbindung an Port {0} fehlgeschlagen", "Imposible vincular la conexión al puerto {0}" },
/* TextUnableToBindUdpSocket */ { "Unable to bind UDP socket to address", "Nicht möglich den UDP socket an eine Adresse zu binden", "Imposible enlazar el UDP socket a la dirección" },
/* TextUnableToCalculatePosition */ { "Unable to calculate position", "Unmöglich die Position zu berechnen", "Imposible calcular la posición" },
/* TextUnableToCreatUdpSocketForReceivingData */ { "Unable to create UDP socket to receive data from control", "Nicht möglich ein UDP socket zu erstellen um Daten von der Zentrale zu empfangen", "Imposible crear UDP socket para recibir datos del control" },
/* TextUnableToCreatUdpSocketForSendingData */ { "Unable to create UDP socket to send data to control", "Nicht möglich ein UDP socket zu erstellen um Daten an die Zentrale zu senden", "Imposible crear UDP socket para enviar datos al control" },
/* TextUnableToCreateSocket */ { "Unable to create socket", "Socket erstellen fehlgeschlagen", "Imposible crear socket" },
/* TextUnableToCreateStorageHandler */ { "Unable to create storage handler", "Unmöglich den Speicher Handler zu erstellen", "Imposible crear manipulador de almacenamiento" },
/* TextUnableToExecuteStreet */ { "Unable to execute street {0}", "Fahrstrasse {0} konnte nicht ausgeführt werden", "Imposibile ejecutar el itinerario {0}" },
/* TextUnableToLock */ { "Unable to lock {0}", "Sperren von {0} nicht möglich", "Imposible bloquear {0}" },
/* TextUnableToReceiveData */ { "Unable to receive data", "Daten empfangen nicht möglich", "Imposible recibir datos" },
/* TextUnableToReserve */ { "Unable to reserve {0}", "Reservieren von {0} nicht möglich", "Imposible reservar {0}" },
/* TextUnableToResolveAddress */ { "Unable to resolve address", "Adresse auflösen fehlgeschalgen", "Imposible resolver la dirección" },
/* TextUnableToSendDataToControl */ { "Unable to send data to control", "Nicht möglich daten an die Zentrale zu senden", "Imposible enviar datos al control" },
/* TextUnblockTrack */ { "Unblock track", "Deblockere Gleis", "Desbloquear vía" },
/* TextUnknownObjectType */ { "Unknown object type", "Unbekannter Objekttyp", "Typo de objecto desconocido" },
/* TextUnloadingControl */ { "Unloading control {0}: {1}", "Entlade Zentrale {0}: {1}", "Descargando control {0}: {1}" },
/* TextVisible */ { "Visible", "Sichtbar", "Visible" },
/* TextWaitAfterRelease */ { "Wait after release (s)", "Wartezeit nach Freigabe (s)", "Tiempo de espera despues liberar (s)" },
/* TextWaitingTimeBetweenMembers */ { "Waiting time between members (ms)", "Wartezeit zwischen Teilnehmern (ms)", "Tiempo de esprera entre los miembros (ms)" },
/* TextWebServerStarted */ { "Webserver started", "Webserver wurde gestartet", "Servidor web encendido" },
/* TextWebServerStopped */ { "Webserver stopped", "Webserver wurde beendet", "Servidor web apagado" },
/* TextWidthIs0 */ { "Width is zero", "Breite ist null", "Anchura está zero" },
/* TextZ21Black2012 */ { "black Z21, hardware 2012", "schwarze Z21, Hardware 2012", "Z21 negro, hardware 2012" },
/* TextZ21Black2013 */ { "black Z21, hardware 2013", "schwarze Z21, Hardware 2013", "Z21 negro, hardware 2013" },
/* TextZ21DoesNotUnderstand */ { "Z21 does not understand our command", "Z21 versteht under Kommando nicht", "Z21 no ha endendido nuestro comando" },
/* TextZ21SmartRail2012 */ { "SmartRail", "SmartRail", "SmartRail" },
/* TextZ21Start2016 */ { "z21 start", "z21 start", "z21 start" },
/* TextZ21Type */ { "Connected to a {0} with firmware version {1}", "Verbunden mit einer {0} mit firmware version", "Conectado a {0} con firmware versión {1}" },
/* TextZ21Unknown */ { "unknown Z21", "unbekannte Z21", "Z21 desconosido" },
/* TextZ21White2013 */ { "white z21", "weisse z21", "z21 blanco" },
// /* Text */ { "", "", "" },
};

Languages::language_t Languages::defaultLanguage = Languages::EN;

Languages::language_t Languages::ParseLanguage(std::string& languageString)
{
	if (languageString.size() < 2)
	{
		return Languages::EN;
	}

	Utils::Utils::StringToUpper(languageString);
	if (languageString[0] == 'D' && languageString[1] == 'E')
	{
		return Languages::DE;
	}

	if (languageString[0] == 'E' && languageString[1] == 'S')
	{
		return Languages::ES;
	}

	return Languages::EN;
}
